### PR TITLE
chore(sturdy): Update to version 0.5.0

### PR DESCRIPTION
**Pull request by nhannah**
### 📰 Summary of changes

- Upgrade dependency and response types

### CODE REVIEW

**Review by willlockwood — APPROVED** [review]
domain lgtm
platform lgtm

**Comment by willlockwood** [comment]
Looks like this needs to run our CI workflows with Dart 3.5, as Brandon did in the sturdy update as well: https://github.com/Betterment/sturdy_http/pull/14

**Comment by nhannah** [comment]
@btrautmann I had to update 2 tests to no longer look for 500's but instead `ServerError`

**Comment by btrautmann** [comment]
Before we merge this, lemme see if I can increase the `pana` score, 110 seems super low

**Review by btrautmann — APPROVED** [review]
domain lgtm
platform lgtm

**Pull request merged**
